### ISSUE TITLE
Possible errors in fluidElement due to redundant input

### ISSUE THREAD

**Issue by brryan** [AFD-Illinois/grim#23]
`fluidElement` constructor takes `const grid &prim` and `const geometry &geom` as inputs, but its functions also take these objects as inputs. This can lead to inconsistencies and errors if, for example, a fluidElement is constructed with centered geometry and primitive variables but its functions are called with geometry and primitive variables evaluated on cell faces.

**Comment by mchandra** [comment]
Fixed in bccc9e0f39a6b3d7bf33800c76daa064de3367f5
